/* *********************************************************************************** */
/* *** ARGUS Enterprise ************************************************************** */
/* *********************************************************************************** */

CREATE OR REPLACE TABLE FACT_PROPERTY_KPI_AE AS (
  SELECT
      MD5(UPPER(p.PROPERTY_ID || '^' || i.PROPERTY_VERSION || '^' || pk.DATE)) AS PK_FACT_PROPERTY_KPI_AE
    , s.MD5_HUB_AE_SCENARIO AS FK_DIMENSION_SCENARIO_AE
    , MD5(UPPER(p.PROPERTY_ID || '^' || i.PROPERTY_VERSION)) AS FK_DIMENSION_PROPERTY_AE
    , pk.DATE AS FK_DIMENSION_DATE
    , CASE pk.CURRENCY_BASIS
        WHEN 0 THEN pd.LOCAL_CURRENCY
        WHEN 1 THEN pd.SCENARIO_CURRENCY
        ELSE NULL
      END AS FK_DIMENSION_CURRENCY
    , pk.*
  FROM
    -- Property --
    DATA_VAULT.PIT_AE_PROPERTY                              i
    INNER JOIN DATA_VAULT.TRANSIENT_{SOURCE}_PROPERTY_VERSION     t ON i.MD5_HUB_AE_PROPERTY =  t.MD5_HUB_AE_PROPERTY AND i.PROPERTY_VERSION = t.PROPERTY_VERSION
    INNER JOIN DATA_VAULT.HUB_AE_PROPERTY                   p  ON i.MD5_HUB_AE_PROPERTY =  p.MD5_HUB_AE_PROPERTY
    INNER JOIN DATA_VAULT.TRANSIENT_AE_PROPERTY_KPI_PIVOTED pk ON i.MD5_HUB_AE_PROPERTY = pk.PROPERTY_AE_KEY     AND i.LDTS_SAT_AE_PROPERTY_KPI     = pk.LDTS
    INNER JOIN DATA_VAULT.SAT_AE_PROPERTY_DETAILS           pd ON i.MD5_HUB_AE_PROPERTY = pd.MD5_HUB_AE_PROPERTY AND i.LDTS_SAT_AE_PROPERTY_DETAILS = pd.LDTS
    -- Scenario --
    INNER JOIN DATA_VAULT.LINK_AE_PROPERTY_SCENARIO         s  ON p.MD5_HUB_AE_PROPERTY =  s.MD5_HUB_AE_PROPERTY
);

CREATE OR REPLACE TABLE FACT_PROPERTY_PAYMENT_AE AS (
  SELECT
      MD5(UPPER(p.PROPERTY_ID || '^' || i.PROPERTY_VERSION || '^' || pp.LINE_ITEM_TYPE_NAME || '^' || pp.DATE)) AS PK_FACT_PROPERTY_PAYMENT_AE
    , s.MD5_HUB_AE_SCENARIO AS FK_DIMENSION_SCENARIO_AE
    , MD5(UPPER(p.PROPERTY_ID || '^' || i.PROPERTY_VERSION)) AS FK_DIMENSION_PROPERTY_AE
    , pp.DATE AS FK_DIMENSION_DATE  
    , CASE pp.CURRENCY_BASIS
        WHEN 0 THEN pd.LOCAL_CURRENCY
        WHEN 1 THEN pd.SCENARIO_CURRENCY
        ELSE NULL
      END AS FK_DIMENSION_CURRENCY
    , pp.CURRENCY_BASIS
    , pp.IS_ASSURED
    , pp.LINE_ITEM_TYPE_NAME AS LINE_ITEM_TYPE
    , pp.ACCOUNT_ID -- TODO: Might be needed as part of the PK in future once we have data
    , pp.VALUATION_YEAR_TOTAL
    , pp.RESALE_YEAR_TOTAL
    , pp.AMOUNT
  FROM
    -- Property --
    DATA_VAULT.PIT_AE_PROPERTY                           i
    INNER JOIN DATA_VAULT.TRANSIENT_{SOURCE}_PROPERTY_VERSION  t ON i.MD5_HUB_AE_PROPERTY =  t.MD5_HUB_AE_PROPERTY AND i.PROPERTY_VERSION = t.PROPERTY_VERSION
    INNER JOIN DATA_VAULT.HUB_AE_PROPERTY                p ON i.MD5_HUB_AE_PROPERTY =  p.MD5_HUB_AE_PROPERTY
    INNER JOIN DATA_VAULT.SAT_AE_PROPERTY_PAYMENT       pp ON i.MD5_HUB_AE_PROPERTY = pp.MD5_HUB_AE_PROPERTY AND i.LDTS_SAT_AE_PROPERTY_PAYMENT = pp.LDTS
    LEFT JOIN DATA_VAULT.SAT_AE_PROPERTY_DETAILS        pd ON i.MD5_HUB_AE_PROPERTY = pd.MD5_HUB_AE_PROPERTY AND i.LDTS_SAT_AE_PROPERTY_DETAILS = pd.LDTS
    -- Scenario --
    INNER JOIN DATA_VAULT.LINK_AE_PROPERTY_SCENARIO s ON p.MD5_HUB_AE_PROPERTY =  s.MD5_HUB_AE_PROPERTY
);

CREATE OR REPLACE TABLE FACT_PROPERTY_CASHFLOW_AE AS (
  SELECT
      MD5(UPPER(p.PROPERTY_ID || '^' || i.PROPERTY_VERSION || '^' || pc.LINE_ITEM_TYPE_NAME || '^' || pc.DATE)) AS PK_FACT_PROPERTY_CASHFLOW_AE
    , s.MD5_HUB_AE_SCENARIO AS FK_DIMENSION_SCENARIO_AE
    , MD5(UPPER(p.PROPERTY_ID || '^' || i.PROPERTY_VERSION)) AS FK_DIMENSION_PROPERTY_AE  
    , pc.MD5_HUB_AE_PROPERTY AS PROPERTY_AE_KEY
    , pc.DATE AS FK_DIMENSION_DATE  
    , CASE pc.CURRENCY_BASIS
        WHEN 0 THEN pd.LOCAL_CURRENCY
        WHEN 1 THEN pd.SCENARIO_CURRENCY
        ELSE NULL
      END AS FK_DIMENSION_CURRENCY    
    , pc.CURRENCY_BASIS
    , pc.IS_ASSURED
    , pc.LINE_ITEM_TYPE_NAME AS LINE_ITEM_TYPE
    , pc.VALUATION_DATE_VALUE
    , pc.RESALE_VALUE
    , pc.UNIT_OF_MEASURE
    , pc.AMOUNT
  FROM
    -- Property --
    DATA_VAULT.PIT_AE_PROPERTY                           i
    INNER JOIN DATA_VAULT.TRANSIENT_{SOURCE}_PROPERTY_VERSION  t ON i.MD5_HUB_AE_PROPERTY =  t.MD5_HUB_AE_PROPERTY AND i.PROPERTY_VERSION = t.PROPERTY_VERSION
    INNER JOIN DATA_VAULT.HUB_AE_PROPERTY                p ON i.MD5_HUB_AE_PROPERTY =  p.MD5_HUB_AE_PROPERTY
    INNER JOIN DATA_VAULT.SAT_AE_PROPERTY_CASHFLOW      pc ON i.MD5_HUB_AE_PROPERTY = pc.MD5_HUB_AE_PROPERTY AND i.LDTS_SAT_AE_PROPERTY_CASHFLOW = pc.LDTS
    LEFT JOIN DATA_VAULT.SAT_AE_PROPERTY_DETAILS        pd ON i.MD5_HUB_AE_PROPERTY = pd.MD5_HUB_AE_PROPERTY AND i.LDTS_SAT_AE_PROPERTY_DETAILS  = pd.LDTS
    -- Scenario --
    INNER JOIN DATA_VAULT.LINK_AE_PROPERTY_SCENARIO s ON p.MD5_HUB_AE_PROPERTY =  s.MD5_HUB_AE_PROPERTY  
);

CREATE OR REPLACE TABLE FACT_LEASE_PAYMENT_AE AS (
  SELECT
      MD5(UPPER(s.PROPERTY_ID || '^' || lp.LEASE_ID || '^' || i.PROPERTY_VERSION || '^' || ly.LINE_ITEM_TYPE_NAME || '^' || ly.DATE)) AS PK_FACT_LEASE_PAYMENT_AE
    , s.MD5_HUB_AE_SCENARIO AS FK_DIMENSION_SCENARIO_AE  
    , MD5(UPPER(lp.PROPERTY_ID || '^' || i.PROPERTY_VERSION)) AS FK_DIMENSION_PROPERTY_AE 
    , MD5(UPPER(lp.PROPERTY_ID || '^' || lp.LEASE_ID || '^' || i.PROPERTY_VERSION)) AS FK_DIMENSION_LEASE_AE
    , ly.DATE AS FK_DIMENSION_DATE  
    , CASE ly.CURRENCY_BASIS
        WHEN 0 THEN pd.LOCAL_CURRENCY
        WHEN 1 THEN pd.SCENARIO_CURRENCY
        ELSE NULL
      END AS FK_DIMENSION_CURRENCY    
    , ly.CURRENCY_BASIS
    , ly.IS_ASSURED
    , ly.LINE_ITEM_TYPE_NAME AS LINE_ITEM_TYPE
    , ly.AMOUNT
  FROM
    -- Lease --
    DATA_VAULT.PIT_AE_LEASE                           i
    INNER JOIN DATA_VAULT.TRANSIENT_{SOURCE}_LEASE_VERSION  t ON  i.MD5_HUB_AE_LEASE =  t.MD5_HUB_AE_LEASE AND i.PROPERTY_VERSION = t.PROPERTY_VERSION
    INNER JOIN DATA_VAULT.SAT_AE_LEASE_PAYMENT       ly ON  i.MD5_HUB_AE_LEASE = ly.MD5_HUB_AE_LEASE AND i.LDTS_SAT_AE_LEASE_PAYMENT = ly.LDTS
    INNER JOIN DATA_VAULT.LINK_AE_LEASE_PROPERTY     lp ON  i.MD5_HUB_AE_LEASE = lp.MD5_HUB_AE_LEASE
    -- Property --
    INNER JOIN DATA_VAULT.PIT_AE_PROPERTY            pp ON lp.MD5_HUB_AE_PROPERTY = pp.MD5_HUB_AE_PROPERTY AND i.PROPERTY_VERSION = pp.PROPERTY_VERSION
    INNER JOIN DATA_VAULT.SAT_AE_PROPERTY_DETAILS    pd ON lp.MD5_HUB_AE_PROPERTY = pd.MD5_HUB_AE_PROPERTY AND pp.LDTS_SAT_AE_PROPERTY_DETAILS = pd.LDTS
    -- Scenario --
    INNER JOIN DATA_VAULT.LINK_AE_PROPERTY_SCENARIO   s ON pp.MD5_HUB_AE_PROPERTY =  s.MD5_HUB_AE_PROPERTY
);

CREATE OR REPLACE TABLE FACT_LEASE_CASHFLOW_AE AS (
  SELECT
      MD5(UPPER(s.PROPERTY_ID || '^' || lp.LEASE_ID || '^' || i.PROPERTY_VERSION || '^' || lc.LINE_ITEM_TYPE_NAME || '^' || lc.DATE)) AS PK_FACT_LEASE_CASHFLOW_AE
    , s.MD5_HUB_AE_SCENARIO AS FK_DIMENSION_SCENARIO_AE  
    , MD5(UPPER(lp.PROPERTY_ID || '^' || i.PROPERTY_VERSION)) AS FK_DIMENSION_PROPERTY_AE 
    , MD5(UPPER(lp.PROPERTY_ID || '^' || lp.LEASE_ID || '^' || i.PROPERTY_VERSION)) AS FK_DIMENSION_LEASE_AE
    , lc.DATE AS FK_DIMENSION_DATE  
    , CASE lc.CURRENCY_BASIS
        WHEN 0 THEN pd.LOCAL_CURRENCY
        WHEN 1 THEN pd.SCENARIO_CURRENCY
        ELSE NULL
      END AS FK_DIMENSION_CURRENCY    
    , lc.CURRENCY_BASIS
    , lc.IS_ASSURED
    , lc.LINE_ITEM_TYPE_NAME AS LINE_ITEM_TYPE
    , lc.LEASE_BEGIN_VALUE
    , lc.VALUATION_DATE_VALUE
    , lc.LEASE_EXPIRY_VALUE
    , lc.RESALE_VALUE
    , lc.UNIT_OF_MEASURE
    , lc.AMOUNT
  FROM
    -- Lease --
    DATA_VAULT.PIT_AE_LEASE                          i
    INNER JOIN DATA_VAULT.TRANSIENT_{SOURCE}_LEASE_VERSION t ON i.MD5_HUB_AE_LEASE =  t.MD5_HUB_AE_LEASE AND i.PROPERTY_VERSION = t.PROPERTY_VERSION
    INNER JOIN DATA_VAULT.SAT_AE_LEASE_CASHFLOW     lc ON i.MD5_HUB_AE_LEASE = lc.MD5_HUB_AE_LEASE AND i.LDTS_SAT_AE_LEASE_CASHFLOW = lc.LDTS
    INNER JOIN DATA_VAULT.LINK_AE_LEASE_PROPERTY    lp ON i.MD5_HUB_AE_LEASE = lp.MD5_HUB_AE_LEASE
  -- Property --
    INNER JOIN DATA_VAULT.PIT_AE_PROPERTY           pp ON lp.MD5_HUB_AE_PROPERTY = pp.MD5_HUB_AE_PROPERTY AND i.PROPERTY_VERSION = pp.PROPERTY_VERSION
    INNER JOIN DATA_VAULT.SAT_AE_PROPERTY_DETAILS   pd ON lp.MD5_HUB_AE_PROPERTY = pd.MD5_HUB_AE_PROPERTY AND pp.LDTS_SAT_AE_PROPERTY_DETAILS = pd.LDTS
    -- Scenario --
    INNER JOIN DATA_VAULT.LINK_AE_PROPERTY_SCENARIO  s ON pp.MD5_HUB_AE_PROPERTY = s.MD5_HUB_AE_PROPERTY
);

CREATE OR REPLACE TABLE FACT_REVEX_PAYMENT_AE AS (
  SELECT
      MD5(UPPER(s.PROPERTY_ID || '^' || rp.REVEX_ID || '^' || i.PROPERTY_VERSION || '^' || ry.LINE_ITEM_TYPE_NAME || '^' || ry.DATE)) AS PK_FACT_REVEX_PAYMENT_AE
    , s.MD5_HUB_AE_SCENARIO AS FK_DIMENSION_SCENARIO_AE  
    , MD5(UPPER(rp.PROPERTY_ID || '^' || i.PROPERTY_VERSION)) AS FK_DIMENSION_PROPERTY_AE 
    , MD5(UPPER(rp.PROPERTY_ID || '^' || rp.REVEX_ID || '^' || i.PROPERTY_VERSION)) AS FK_DIMENSION_REVEX_AE
    , ry.DATE AS FK_DIMENSION_DATE
    , CASE ry.CURRENCY_BASIS
        WHEN 0 THEN pd.LOCAL_CURRENCY
        WHEN 1 THEN pd.SCENARIO_CURRENCY
        ELSE NULL
      END AS FK_DIMENSION_CURRENCY
    , ry.CURRENCY_BASIS
    , ry.IS_ASSURED
    , ry.RESULTSET AS RESULT_SET
    , ry.LINE_ITEM_TYPE_NAME AS LINE_ITEM_TYPE
    , ry.AMOUNT
  FROM
    -- RevEx --
    DATA_VAULT.PIT_AE_REVEX                          i
    INNER JOIN DATA_VAULT.TRANSIENT_{SOURCE}_REVEX_VERSION t ON i.MD5_HUB_AE_REVEX =  t.MD5_HUB_AE_REVEX AND i.PROPERTY_VERSION = t.PROPERTY_VERSION
    INNER JOIN DATA_VAULT.SAT_AE_REVEX_PAYMENT      ry ON i.MD5_HUB_AE_REVEX = ry.MD5_HUB_AE_REVEX AND i.LDTS_SAT_AE_REVEX_PAYMENT = ry.LDTS
    INNER JOIN DATA_VAULT.LINK_AE_REVEX_PROPERTY    rp ON i.MD5_HUB_AE_REVEX = rp.MD5_HUB_AE_REVEX
  -- Property --
    INNER JOIN DATA_VAULT.PIT_AE_PROPERTY           pp ON rp.MD5_HUB_AE_PROPERTY = pp.MD5_HUB_AE_PROPERTY AND i.PROPERTY_VERSION = pp.PROPERTY_VERSION
    INNER JOIN DATA_VAULT.SAT_AE_PROPERTY_DETAILS   pd ON rp.MD5_HUB_AE_PROPERTY = pd.MD5_HUB_AE_PROPERTY AND pp.LDTS_SAT_AE_PROPERTY_DETAILS = pd.LDTS
    -- Scenario --
    INNER JOIN DATA_VAULT.LINK_AE_PROPERTY_SCENARIO  s ON pp.MD5_HUB_AE_PROPERTY =  s.MD5_HUB_AE_PROPERTY
);

CREATE OR REPLACE TABLE FACT_REVEX_CASHFLOW_AE AS (
  SELECT
      MD5(UPPER(s.PROPERTY_ID || '^' || rp.REVEX_ID || '^' || i.PROPERTY_VERSION || '^' || rc.LINE_ITEM_TYPE_NAME || '^' || rc.DATE)) AS PK_FACT_REVEX_CASHFLOW_AE
    , s.MD5_HUB_AE_SCENARIO AS FK_DIMENSION_SCENARIO_AE  
    , MD5(UPPER(rp.PROPERTY_ID || '^' || i.PROPERTY_VERSION)) AS FK_DIMENSION_PROPERTY_AE 
    , MD5(UPPER(rp.PROPERTY_ID || '^' || rp.REVEX_ID || '^' || i.PROPERTY_VERSION)) AS FK_DIMENSION_REVEX_AE
    , rc.DATE AS FK_DIMENSION_DATE  
    , CASE rc.CURRENCY_BASIS
        WHEN 0 THEN pd.LOCAL_CURRENCY
        WHEN 1 THEN pd.SCENARIO_CURRENCY
        ELSE NULL
      END AS FK_DIMENSION_CURRENCY
    , rc.CURRENCY_BASIS
    , rc.IS_ASSURED
    , rc.LINE_ITEM_TYPE_NAME AS LINE_ITEM_TYPE
    , rc.UNIT_OF_MEASURE
    , rc.INITIAL_ANNUAL_AMOUNT
    , rc.AMOUNT
  FROM
    -- Revex --
    DATA_VAULT.PIT_AE_REVEX                          i
    INNER JOIN DATA_VAULT.TRANSIENT_{SOURCE}_REVEX_VERSION t ON i.MD5_HUB_AE_REVEX =  t.MD5_HUB_AE_REVEX AND i.PROPERTY_VERSION = t.PROPERTY_VERSION
    INNER JOIN DATA_VAULT.SAT_AE_REVEX_CASHFLOW     rc ON i.MD5_HUB_AE_REVEX = rc.MD5_HUB_AE_REVEX AND i.LDTS_SAT_AE_REVEX_CASHFLOW = rc.LDTS
    INNER JOIN DATA_VAULT.LINK_AE_REVEX_PROPERTY    rp ON i.MD5_HUB_AE_REVEX = rp.MD5_HUB_AE_REVEX
  -- Property --
    INNER JOIN DATA_VAULT.PIT_AE_PROPERTY           pp ON rp.MD5_HUB_AE_PROPERTY = pp.MD5_HUB_AE_PROPERTY AND  i.PROPERTY_VERSION = pp.PROPERTY_VERSION
    INNER JOIN DATA_VAULT.SAT_AE_PROPERTY_DETAILS   pd ON rp.MD5_HUB_AE_PROPERTY = pd.MD5_HUB_AE_PROPERTY AND pp.LDTS_SAT_AE_PROPERTY_DETAILS = pd.LDTS
    -- Scenario --
    INNER JOIN DATA_VAULT.LINK_AE_PROPERTY_SCENARIO  s ON pp.MD5_HUB_AE_PROPERTY = s.MD5_HUB_AE_PROPERTY
);

CREATE OR REPLACE TABLE FACT_LOAN_PAYMENT_AE AS (
  SELECT
      MD5(UPPER(s.PROPERTY_ID || '^' || ly.LOAN_ID || '^' || i.PROPERTY_VERSION || '^' || lp.LINE_ITEM_NAME || '^' || lp.DATE)) AS PK_FACT_LOAN_PAYMENT_AE
    , s.MD5_HUB_AE_SCENARIO AS FK_DIMENSION_SCENARIO_AE  
    , MD5(UPPER(ly.PROPERTY_ID || '^' || i.PROPERTY_VERSION)) AS FK_DIMENSION_PROPERTY_AE 
    , MD5(UPPER(ly.PROPERTY_ID || '^' || ly.LOAN_ID || '^' || i.PROPERTY_VERSION)) AS FK_DIMENSION_LOAN_AE  
    , lp.DATE AS FK_DIMENSION_DATE  
    , CASE lp.CURRENCY_BASIS
        WHEN 0 THEN pd.LOCAL_CURRENCY
        WHEN 1 THEN pd.SCENARIO_CURRENCY
        ELSE NULL
      END AS FK_DIMENSION_CURRENCY
    , lp.CURRENCY_BASIS
    , lp.IS_ASSURED_RESULT_SET
    , lp.RESULT_SET
    , lp.LINE_ITEM_NAME
    , lp.ACCOUNT_CODE
    , lp.AMOUNT
  FROM
    -- Loan --
    DATA_VAULT.PIT_AE_LOAN                          i
    INNER JOIN DATA_VAULT.TRANSIENT_{SOURCE}_LOAN_VERSION t ON i.MD5_HUB_AE_LOAN =  t.MD5_HUB_AE_LOAN AND i.PROPERTY_VERSION = t.PROPERTY_VERSION
    INNER JOIN DATA_VAULT.SAT_AE_LOAN_PAYMENT      lp ON i.MD5_HUB_AE_LOAN = lp.MD5_HUB_AE_LOAN AND i.LDTS_SAT_AE_LOAN_PAYMENT = lp.LDTS
    INNER JOIN DATA_VAULT.LINK_AE_LOAN_PROPERTY    ly ON i.MD5_HUB_AE_LOAN = ly.MD5_HUB_AE_LOAN
  -- Property --
    INNER JOIN DATA_VAULT.PIT_AE_PROPERTY          pp ON ly.MD5_HUB_AE_PROPERTY = pp.MD5_HUB_AE_PROPERTY AND i.PROPERTY_VERSION = pp.PROPERTY_VERSION
    INNER JOIN DATA_VAULT.SAT_AE_PROPERTY_DETAILS  pd ON ly.MD5_HUB_AE_PROPERTY = pd.MD5_HUB_AE_PROPERTY AND pp.LDTS_SAT_AE_PROPERTY_DETAILS = pd.LDTS
    -- Scenario --
    INNER JOIN DATA_VAULT.LINK_AE_PROPERTY_SCENARIO s ON pp.MD5_HUB_AE_PROPERTY =  s.MD5_HUB_AE_PROPERTY  
);