/* *********************************************************************************** */
/* *** ARGUS Enterprise ************************************************************** */
/* *********************************************************************************** */

CREATE OR REPLACE TABLE DIMENSION_PROPERTY_AE AS (
  SELECT
      MD5(UPPER(e.PROPERTY_ID || '^' || i.PROPERTY_VERSION)) AS PK_DIMENSION_PROPERTY_AE
    , e.EXTERNAL_PROPERTY_ID
    , i.PROPERTY_VERSION
    , d.PROPERTY_NAME
    , d.VALUATION_DATE
    , d.RESALE_DATE
    , d.PROPERTY_TYPE -- TODO: needs decoding
    , d.LOCAL_CURRENCY -- TODO: should this go to a junk dimension?
    , d.PROPERTY_AREA_MEASURE -- TODO: needs decoding AND should go into a junk dimension?
    , l.ADDRESS
    , d.SCENARIO_ARCHIVED
  FROM
    DATA_VAULT.PIT_AE_PROPERTY                          i
    INNER JOIN DATA_VAULT.TRANSIENT_{SOURCE}_PROPERTY_VERSION t ON i.MD5_HUB_AE_PROPERTY = t.MD5_HUB_AE_PROPERTY AND i.PROPERTY_VERSION = t.PROPERTY_VERSION
    LEFT JOIN DATA_VAULT.LINK_AE_PROPERTY_EXT_PROPERTY  e ON i.MD5_HUB_AE_PROPERTY = e.MD5_HUB_AE_PROPERTY
    LEFT JOIN DATA_VAULT.SAT_AE_PROPERTY_DETAILS        d ON i.MD5_HUB_AE_PROPERTY = d.MD5_HUB_AE_PROPERTY AND i.LDTS_SAT_AE_PROPERTY_DETAILS = d.LDTS
    LEFT JOIN DATA_VAULT.SAT_AE_PROPERTY_LOCATION       l ON i.MD5_HUB_AE_PROPERTY = l.MD5_HUB_AE_PROPERTY AND i.LDTS_SAT_AE_PROPERTY_LOCATION = l.LDTS
);

CREATE OR REPLACE TABLE DIMENSION_LEASE_AE AS (
  SELECT
      MD5(UPPER(p.PROPERTY_ID || '^' || p.LEASE_ID || '^' || i.PROPERTY_VERSION)) AS PK_DIMENSION_LEASE_AE
    , e.EXTERNAL_LEASE_ID
    , d.IS_BASE_LEASE
    , d.TENANT_NAME
    , d.SUITE
    , d.TENURE
    , d.LEASE_TYPE -- TODO: needs decoding
    , d.CUSTOM_LEASE_TYPE
    , d.LEASE_BEGIN
    , d.LEASE_EXPIRY
    , d.EXPIRY_TYPE -- TODO: needs decoding
    , d.EARLIEST_BREAK
    , d.REMAINING_TERM_DAYS
    , d.LEASE_STATUS
    , d.LEASE_PERIOD_DAYS
    , d.MARKET_LEASE_PROFILE_NAME
    , d.RECOVERY_STRUCTURE_NAME
    , d.CPI_TYPE -- TODO: needs decoding
    , d.CPI_TIMING
    , d.CPI_RATE_OR_INDEX
  FROM
    DATA_VAULT.PIT_AE_LEASE                          i
    INNER JOIN DATA_VAULT.TRANSIENT_{SOURCE}_LEASE_VERSION t ON i.MD5_HUB_AE_LEASE = t.MD5_HUB_AE_LEASE AND i.PROPERTY_VERSION = t.PROPERTY_VERSION
    INNER JOIN DATA_VAULT.LINK_AE_LEASE_PROPERTY     p ON i.MD5_HUB_AE_LEASE = p.MD5_HUB_AE_LEASE
    LEFT JOIN DATA_VAULT.LINK_AE_LEASE_EXT_LEASE     e ON i.MD5_HUB_AE_LEASE = e.MD5_HUB_AE_LEASE
    LEFT JOIN DATA_VAULT.SAT_AE_LEASE_DETAILS        d ON i.MD5_HUB_AE_LEASE = d.MD5_HUB_AE_LEASE AND i.LDTS_SAT_AE_LEASE_DETAILS = d.LDTS
);

CREATE OR REPLACE TABLE DIMENSION_REVEX_AE AS (
  SELECT
      MD5(UPPER(p.PROPERTY_ID || '^' || p.REVEX_ID || '^' || i.PROPERTY_VERSION)) AS PK_DIMENSION_REVEX_AE
    , d.REVEX_NAME
    , d.REVEX_TYPE      -- TODO: needs decoding
    , d.ACCOUNT_CODE
    , d.SORT_ORDER
    , d.BASIS           -- TODO: needs decoding
    , d.START_DATE
    , d.UNIT_OF_MEASURE -- TODO: needs decoding    
  FROM
    DATA_VAULT.PIT_AE_REVEX                          i
    INNER JOIN DATA_VAULT.TRANSIENT_{SOURCE}_REVEX_VERSION t ON i.MD5_HUB_AE_REVEX = t.MD5_HUB_AE_REVEX AND i.PROPERTY_VERSION = t.PROPERTY_VERSION  
    INNER JOIN DATA_VAULT.LINK_AE_REVEX_PROPERTY     p ON i.MD5_HUB_AE_REVEX = p.MD5_HUB_AE_REVEX
    LEFT JOIN DATA_VAULT.SAT_AE_REVEX_DETAILS        d ON i.MD5_HUB_AE_REVEX = d.MD5_HUB_AE_REVEX AND i.LDTS_SAT_AE_REVEX_DETAILS = d.LDTS
);

CREATE OR REPLACE TABLE DIMENSION_LOAN_AE AS (
  SELECT
      MD5(UPPER(p.PROPERTY_ID || '^' || p.LOAN_ID || '^' || i.PROPERTY_VERSION)) AS PK_DIMENSION_LOAN_AE
    , d.LOAN_NAME
    , d.LOAN_TYPE -- TODO: needs decoding
    , d.HOW_INPUT -- TODO: needs decoding
    , d.SENIORITY -- TODO: needs decoding
    , d.LOAN_DATE
    , d.LOAN_END 
  FROM
    DATA_VAULT.PIT_AE_LOAN                          i
    INNER JOIN DATA_VAULT.TRANSIENT_{SOURCE}_LOAN_VERSION t ON i.MD5_HUB_AE_LOAN = t.MD5_HUB_AE_LOAN AND i.PROPERTY_VERSION = t.PROPERTY_VERSION  
    INNER JOIN DATA_VAULT.LINK_AE_LOAN_PROPERTY     p ON i.MD5_HUB_AE_LOAN = p.MD5_HUB_AE_LOAN
    LEFT JOIN DATA_VAULT.SAT_AE_LOAN_DETAILS        d ON i.MD5_HUB_AE_LOAN = d.MD5_HUB_AE_LOAN AND i.LDTS_SAT_AE_LOAN_DETAILS = d.LDTS
);