/* *********************************************************************************** */
/* *** ARGUS Taliance **************************************************************** */
/* *********************************************************************************** */

/* create tables in data vault to be pivoted */

CREATE OR REPLACE TRANSIENT TABLE DATA_VAULT.TRANSIENT_AT_DIMENSION_FLOW AS
  SELECT
      MD5(UPPER(f.SCENARIO_ID || '^' || f.ENTITY_ID || '^' || COALESCE(TO_VARCHAR(f.DIMENSION_ID), ''))) AS PK_DIMENSION_FLOW_AT
    , f.MD5_HUB_AT_SCENARIO AS FK_DIMENSION_SCENARIO_AT
    , f.MD5_HUB_AT_ENTITY AS FK_DIMENSION_ENTITY_AT
    , f.DATE AS FK_DIMENSION_DATE    
    , a.DIMENSION_LABEL AS DIMENSION
    , l.LINE_ITEM_CODE AS LINE_ITEM -- FIXME use LINE_ITEM_LABEL
    , l.LINE_ITEM_CATEGORY_CODE AS CATEGORY
    , l.LINE_ITEM_TYPE AS TYPE
    , d.VALUE
  FROM DATA_VAULT.LINK_AT_FACT f
    INNER JOIN DATA_VAULT.SAT_AT_FACT_DETAILS d ON f.MD5_LINK_AT_FACT = d.MD5_LINK_AT_FACT
    INNER JOIN DATA_VAULT.SAT_AT_LINE_ITEM_DETAILS l ON f.MD5_HUB_AT_LINE_ITEM = l.MD5_HUB_AT_LINE_ITEM
    LEFT OUTER JOIN DATA_VAULT.SAT_AT_DIMENSION_DETAILS a ON f.MD5_HUB_AT_DIMENSION = a.MD5_HUB_AT_DIMENSION
  WHERE
    l.LINE_ITEM_CHARACTERISTIC = FALSE
    AND UPPER(l.LINE_ITEM_TYPE) <> 'NUMERIC'
    AND UPPER(l.LINE_ITEM_STOCK_FLOW) = 'FLOW'
    AND d.VALUE IS NOT NULL
;

CREATE OR REPLACE TRANSIENT TABLE DATA_VAULT.TRANSIENT_AT_DIMENSION_KPI AS
  SELECT
      MD5(UPPER(f.SCENARIO_ID || '^' || f.ENTITY_ID || '^' || COALESCE(TO_VARCHAR(f.DIMENSION_ID), ''))) AS PK_DIMENSION_KPI_AT
    , f.MD5_HUB_AT_SCENARIO AS FK_DIMENSION_SCENARIO_AT
    , f.MD5_HUB_AT_ENTITY AS FK_DIMENSION_ENTITY_AT
    , f.DATE AS FK_DIMENSION_DATE    
    , a.DIMENSION_LABEL AS DIMENSION
    , l.LINE_ITEM_CODE AS LINE_ITEM -- FIXME use LINE_ITEM_LABEL
    , l.LINE_ITEM_CATEGORY_CODE AS CATEGORY
    , l.LINE_ITEM_TYPE AS TYPE
    , d.VALUE
  FROM DATA_VAULT.LINK_AT_FACT f
    INNER JOIN DATA_VAULT.SAT_AT_FACT_DETAILS d ON f.MD5_LINK_AT_FACT = d.MD5_LINK_AT_FACT
    INNER JOIN DATA_VAULT.SAT_AT_LINE_ITEM_DETAILS l ON f.MD5_HUB_AT_LINE_ITEM = l.MD5_HUB_AT_LINE_ITEM
    LEFT OUTER JOIN DATA_VAULT.SAT_AT_DIMENSION_DETAILS a ON f.MD5_HUB_AT_DIMENSION = a.MD5_HUB_AT_DIMENSION
  WHERE
    l.LINE_ITEM_CHARACTERISTIC = FALSE
    AND UPPER(l.LINE_ITEM_TYPE) <> 'NUMERIC'
    AND UPPER(l.LINE_ITEM_STOCK_FLOW) = 'STOCK'
    AND d.VALUE IS NOT NULL
;

CREATE OR REPLACE TRANSIENT TABLE DATA_VAULT.TRANSIENT_AT_DIMENSION_CHARACTERISTIC AS
SELECT
    f.MD5_HUB_AT_ENTITY
  , a.DIMENSION_LABEL AS DIMENSION
  , l.LINE_ITEM_CODE AS LINE_ITEM -- FIXME use LINE_ITEM_LABEL
  , l.LINE_ITEM_TYPE AS TYPE
  , d.VALUE
FROM DATA_VAULT.LINK_AT_FACT f
  INNER JOIN DATA_VAULT.SAT_AT_FACT_DETAILS d ON f.MD5_LINK_AT_FACT = d.MD5_LINK_AT_FACT
  INNER JOIN DATA_VAULT.SAT_AT_LINE_ITEM_DETAILS l ON f.MD5_HUB_AT_LINE_ITEM = l.MD5_HUB_AT_LINE_ITEM
  LEFT OUTER JOIN DATA_VAULT.SAT_AT_DIMENSION_DETAILS a ON f.MD5_HUB_AT_DIMENSION = a.MD5_HUB_AT_DIMENSION
WHERE
  l.LINE_ITEM_CHARACTERISTIC = TRUE
  AND d.VALUE IS NOT NULL
;
     
CREATE OR REPLACE TRANSIENT TABLE DATA_VAULT.TRANSIENT_AT_DIMENSION_ENTITY AS
SELECT
    e.MD5_HUB_AT_ENTITY
  , d.ENTITY_LABEL AS ENTITY
  , y.ENTITY_TYPE_LABEL AS ENTITY_TYPE
  , d.BEGIN_DATE
  , d.END_DATE
FROM
  DATA_VAULT.HUB_AT_ENTITY e
  INNER JOIN DATA_VAULT.SAT_AT_ENTITY_DETAILS d ON e.MD5_HUB_AT_ENTITY = d.MD5_HUB_AT_ENTITY
  INNER JOIN DATA_VAULT.LINK_AT_ENTITY_ENTITY_TYPE t ON e.MD5_HUB_AT_ENTITY = t.MD5_HUB_AT_ENTITY
  INNER JOIN DATA_VAULT.SAT_AT_ENTITY_TYPE_DETAILS y ON t.MD5_HUB_AT_ENTITY_TYPE = y.MD5_HUB_AT_ENTITY_TYPE
;
